{% set name = "pyobjc-framework-SystemConfiguration" %}
{% set version = "12.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name.replace('-', '_').lower() }}/{{ name.replace('-', '_').lower() }}-{{ version }}.tar.gz
  sha256: 90fe04aa059876a21626931c71eaff742a27c79798a46347fd053d7008ec496e
  #patches:
    #- patches/0001-Remove-werror-from-compile-flags.patch

build:
  number: 1
  script:
    # force pyobjc to use conda-forge's chosen SDK
    - export CFLAGS="${CFLAGS} -isysroot ${SDKROOT:-$CONDA_BUILD_SYSROOT}"
    # force ignoring invalid compiler flag (-Wl,-export-dynamic)
    - export CFLAGS="${CFLAGS} -Wno-unused-command-line-argument"  # [py == 37 or py == 38]
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [(not osx) or py2k or python_impl == 'pypy' or (arm64 and py < 39)]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - setuptools
    - wheel
    - pip
  run:
    - python
    - pyobjc-core >={{ version }}
    - pyobjc-framework-cocoa >={{ version }}

test:
  imports:
    - PyObjCTools
    - SystemConfiguration
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ronaldoussoren/pyobjc
  summary: Wrappers for the framework SystemConfiguration on macOS
  doc_url: https://pythonhosted.org/pyobjc-framework-SystemConfiguration/
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - rxm7706
